### ISSUE TITLE
https://gyazo.com/905b3898a7316136858e135affd0bfe8

### ISSUE THREAD

**Issue by ghost** [rbenv/rbenv-installer#12]
https://gyazo.com/905b3898a7316136858e135affd0bfe8

**Comment by llimllib** [comment]
In order to have rbenv-installer run successfully, you need to do:

```
export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"
curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash
```

I also wish rbenv-installer would not run doctor at the end of the script

**Comment by LemonAndroid** [comment]
ok, are you allowed to merge a PR that does this automatically?
