### ISSUE TITLE
Error: invalid option: --without-ruby-build

### ISSUE THREAD

**Issue by davidstosik** [rbenv/rbenv-installer#15]
I'm getting this error when installing rbenv with Homebrew:

```
Error: invalid option: --without-ruby-build
```

**Comment by Jonnie-Cache** [comment]
Having the same problem.

**Comment by Odalrick** [comment]
I had the same problem; running `brew install rbenv` first seems to have solved it. That is run the command that it tries to run but without "--without-ruby-build"; I guess that option has been removed upstream.

**Comment by sphanley** [comment]
Is this script still maintained? There's two different open PRs to fix this issue - can one of them please be merged?

**Comment by docwhat** [comment]
@mislav It looks like rbenv-installer needs a little love.

**Comment by mislav** [comment]
Sorry all. For some reason, I wasn't watching this repo, so I wasn't notified of any activity until I got @-mentioned. 🤦
