### ISSUE TITLE
Identify invalid PATH precedence

### ISSUE THREAD

**Issue by adamkaplan** [rbenv/rbenv-installer#18]
Please add a check for PATH resolution precedence.

I had the `rbenv` shims in my PATH, set via `rbenv init` in my shell profile. Unfortunately other shell configuration statements accidentally pushed the shims to the _end of the PATH list_, causing System Ruby binaries to be chosen.

My path looks like this:
```
> echo $PATH
~/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:~/.rbenv/shims
```

`rbenv-doctor` issued an all clear:
```
> curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash
Checking for `rbenv' in PATH: /usr/local/bin/rbenv
Checking for rbenv shims in PATH: OK
Checking `rbenv install' support: /usr/local/bin/rbenv-install (ruby-build 20190423)
Counting installed Ruby versions: 1 versions
Checking RubyGems settings: OK
Auditing installed plugins: OK
```

However it is wrong. `/usr/bin/gem` is still chosen over the `rbenv` version.

I'm not sure the best way to do this. Perhaps doing a `which gem` and looking for the shim path?

**Comment by fernandodev** [comment]
Ideally, we should have a way to skip doctor-script during installation. Especially for Docker setup, this is very annoying.

https://github.com/rbenv/rbenv-installer/blob/108c12307621a0aa06f19799641848dde1987deb/bin/rbenv-installer#L110

**Comment by mislav** [comment]
@fernandodev We no longer automatically run the doctor script after installation. 👍
