### ISSUE TITLE
PATH

### ISSUE THREAD

**Issue by alanoe** [rbenv/rbenv-installer#28]
I'm having issues trying to use rbenv-installer. It seems that the rbenv-doctor script requires that \~/.rbenv/bin is added to PATH and I everything goes fine if I add the env variable *before* running rbenv-installer. However, checking the code, I see the following messages printed after rbenv-doctor runs: "Note that this installer doesn't yet configure your shell startup files. You'll want to ensure that \~/.rbenv/bin is added to PATH.". If I'm required to manually set up PATH *before* running rbenv-installer, that warning does not make any sense.

**Comment by docwhat** [comment]
The message is telling you to do that after install `rbenv`, you need to setup your `PATH`.

`rbenv init` will tell you the same thing.

`rbenv-doctor` work fine without `$RBENV_ROOT/bin` in your `PATH`.

```sh
❯ wget -q https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor -O- | bash
Checking for `rbenv' in PATH: /usr/local/bin/rbenv
Checking for rbenv shims in PATH: not found
  The directory `/Users/docwhat/.rbenv/shims' must be present in PATH for rbenv to work.
  Please run `rbenv init' and follow the instructions.

Checking `rbenv install' support: /usr/local/bin/rbenv-install (ruby-build 20210423)
Counting installed Ruby versions: none
  There aren't any Ruby versions installed under `/Users/docwhat/.rbenv/versions'.
  You can install Ruby versions like so: rbenv install 2.2.4
Checking RubyGems settings: OK
Auditing installed plugins: OK
```

**Comment by mislav** [comment]
Thanks, @docwhat.

@alanoe Yeah, the current state of installer isn't all that great, because there is no simple way for installers to add stuff to your PATH in an automated fashion, so that's something that each user has to do themselves.

You're _not_ required to edit PATH before the installer, but you are supposed to react to the warning that's printed during the installer/doctor phase. The warning will always be printed.

**Comment by manwelbugeja** [comment]
Hi I had the same issue. The way I solved it is by installing ruby-build as a plugin as follows:

`mkdir -p "$(rbenv root)"/plugins`
`git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build`
