### ISSUE TITLE
You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.

### ISSUE THREAD

**Issue by hchaozhe** [rbenv/rbenv-installer#4]
Hi @mislav  I have a similar issue as [This one](https://github.com/rbenv/ruby-build/issues/168).

I just noticed that you closed that issue so I open a new issue.
 

I installed rbenv using [rbenv-installer](https://github.com/rbenv/rbenv-installer) 

I have added 
>eval "$(rbenv init -)"  

to \.bash_profile, and if I run

> $ echo $PATH | tr ':' $'\n'

I got

>/Users/username/.rbenv/shims
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin

I also run the rbenv-doctor using
 
> curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash

What I have got is 
>Checking for `rbenv' in PATH: /usr/local/bin/rbenv
Checking for rbenv shims in PATH: OK
Checking `rbenv install' support: /usr/local/bin/rbenv-install (ruby-build 20160913)
Counting installed Ruby versions: 1 versions
Checking RubyGems settings: OK
Auditing installed plugins: OK

The version of ruby I installed is 2.2.4 using 
>rbenv install 2.2.4

and there is a corresponding folder under ~/.rbenv/versions

And the system ruby I have is 
>ruby -v
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]

But when I type in 

> $ gem install bundler
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.

I have tried install and uninstall many times, and try many methods posted online but none of those apply.

Thank you in advance!

**Comment by mattbrictson** [comment]
If you are trying to install the bundler gem into the system Ruby, then this is working exactly as expected. The system Ruby is not writable by a normal user; if you want to modify the system Ruby's gems, you need to use `sudo gem install`.

On the other hand, if you are trying to install the bundler gem into your rbenv-managed Ruby (2.2.4), then you need to activate it first.

Activate it for the current shell using:

```
rbenv shell 2.2.4
```

Or activate it and make it the default Ruby from now on:

```
rbenv global 2.2.4
```

After that, you should be able to run:

```
gem install bundler
```

**Comment by hchaozhe** [comment]
Thank you @mattbrictson for your help!
I think I didn't really have Ruby 2.2.4  and that is why my version folder is empty. And when I run gem it still end-up using the ruby 2.0.0 in my system which I don't have the permission of course.

I install ruby 2.2.4 and then follow your suggestion I get 

> gem install bundler

working smoothly!
