### ISSUE TITLE
URL's mentioned in README 404's

### ISSUE THREAD

**Issue by dbackeus** [rbenv/rbenv-installer#42]
https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer 404's.

I guess eg. `https://raw.githubusercontent.com/rbenv/rbenv-installer/main/bin/rbenv-installer` should be used instead.

**Comment by mislav** [comment]
It works for me:
```
$ curl -sL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer | head
#!/bin/bash
set -e

homebrew=
type -p brew >/dev/null && homebrew=1

try_bash_extension() {
  if [ -x src/configure ]; then
    # shellcheck disable=SC2015
    src/configure && make -C src || {
```
Must have been a temporary glitch!
