### ISSUE TITLE
rbenv: no such command `root'

### ISSUE THREAD

**Issue by stdedos** [rbenv/rbenv-installer#5]
https://github.com/rbenv/rbenv-installer/blob/79eda38051f349508335f1a51e5dc54b8654a5df/bin/rbenv-doctor#L74

OS: Ubuntu 12.04.5 LTS

I am not sure of what other details may be required (from here: https://github.com/rbenv/rbenv/blob/master/README.md#installation)

**Comment by stdedos** [comment]
Could be either connectivity issue or `apt-get` old version (I was naive enough to try it like that)

**Comment by mislav** [comment]
`rbenv root` was [added in v0.3.0](https://github.com/rbenv/rbenv/commit/be7dcc0ad84ad8abc5652b1e80dedff098a53a08). Your installation of rbenv must have been ancient! I don't think it's worth adjusting this script for such old versions of rbenv.
