### ISSUE TITLE
Yes, I added `-O` at https://github.com/rbenv/ruby-build/commit/e12c32f71245d4238c8e085ad7484bbcb972f602

### ISSUE THREAD

**Issue by Sec32fun32** [rbenv/rbenv-installer#51]
Yes, I added `-O` at https://github.com/rbenv/ruby-build/commit/e12c32f71245d4238c8e085ad7484bbcb972f602

_Originally posted by @hsbt in https://github.com/rbenv/ruby-build/pull/2430#discussion_r1703458220_

**Comment by hsbt** [comment]
@mislav Can you close this? or could you add write or admin grant of this repository to me?
